### ISSUE TITLE
能用apiGet的模式写个例子出来吗？

### ISSUE THREAD

**Issue by taany6210** [xiaoyaoyou1212/ViseUtils#1]
`@Override
    public ApiResult<T> call(ResponseBody responseBody) {
        Gson gson = new Gson();
        ApiResult<T> apiResult = new ApiResult<T>();
        apiResult.setStatus(-1);
        try {
            String json = responseBody.string();
            if (clazz.equals(String.class)) {
                apiResult.setData((T) json);
                apiResult.setStatus(0);
            } else {
                ApiResult result = parseApiResult(json, apiResult);
                if (result != null) {
                    apiResult = result;
                    if (apiResult.getData() != null) {
                        T data = gson.fromJson(apiResult.getData().toString(), clazz);
                        apiResult.setData(data);
                    } else {
                        apiResult.setMessage("ApiResult's data is null");
                    }
                } else {
                    apiResult.setMessage("json is null");
                }
            }
        } catch (JSONException e) {
            e.printStackTrace();
            apiResult.setMessage(e.getMessage());
        } catch (IOException e) {
            e.printStackTrace();
            apiResult.setMessage(e.getMessage());
        } finally {
            responseBody.close();
        }
        return apiResult;
    }`

我觉得这个方法这里应该返回 T ，code 这些可以在这里统一的进行处理下。我试了这个apiGet这个方法，总是搞不对类型。谢谢大神教教我。

**Comment by xiaoyaoyou1212** [comment]
@taany6210 ApiResult这个转换是针对服务器返回类型是固定的code、msg、data这种形式，至于code的判定可以在后面加一层转换就行，后面有通过ApiDataFunc转换，最后返回的是T，你也可以替换成自定义的转换类，每个服务器定义的都不同，这里只是介绍一种转换思路。
注：貌似提问的库搞错了，这个应该是XSnow库中的
